name: test_profile
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  get_it: ^7.6.4
  go_router: ^13.0.0
  injectable: ^2.3.2
  image_picker: ^1.0.5
  path_provider: ^2.1.3
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  cupertino_icons: ^1.0.6
  flutter_multi_formatter: ^2.12.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  freezed: ^2.4.5
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/avatars/
    - assets/categories/
    - assets/products/

